<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AdaptationRules" nsURI="platform:/resource/AdaptationRules/model/AdaptationRules.ecore"
    nsPrefix="AdaptationRules">
  <eClassifiers xsi:type="ecore:EClass" name="Context2EssentialIFML">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ContextML/model/contextML.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/EssentialIFML/model/essentialIFML.ecore#/0/EssentialIFMLModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateWindowsAndLinks">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ContextML/model/contextML.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/EssentialIFML/model/essentialIFML.ecore#/0/ViewContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role2Window">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ContextML/model/contextML.ecore#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/EssentialIFML/model/essentialIFML.ecore#/0/ViewContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User2Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ContextML/model/contextML.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/EssentialIFML/model/essentialIFML.ecore#/0/Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserColorBlind2AdaptColorBlind">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ContextML/model/contextML.ecore#//ColorBlind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/EssentialIFML/model/essentialIFML.ecore#/0/LightBackgroundColor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserAge2ScreenZoom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ContextML/model/contextML.ecore#//Age"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/EssentialIFML/model/essentialIFML.ecore#/0/ZoomScreen"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Age2IncreaseButtonSize">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ContextML/model/contextML.ecore#//Age"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/EssentialIFML/model/essentialIFML.ecore#/0/Event"/>
  </eClassifiers>
</ecore:EPackage>
