<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testTGG" nsURI="platform:/resource/testTGG/model/testTGG.ecore"
    nsPrefix="testTGG">
  <eClassifiers xsi:type="ecore:EClass" name="ContextToEssentialIFML">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ContextML/model/contextML.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/EssentialIFML/model/essentialIFML.ecore#//EssentialIFMLModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateWindowForAll">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ContextML/model/contextML.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/EssentialIFML/model/essentialIFML.ecore#//EssentialIFMLModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAdminWindow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ContextML/model/contextML.ecore#//Admin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/EssentialIFML/model/essentialIFML.ecore#//DetailsText"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateUserWindow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ContextML/model/contextML.ecore#//Student"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/EssentialIFML/model/essentialIFML.ecore#//Details"/>
  </eClassifiers>
</ecore:EPackage>
